version: 2
plugins:
  structure:
    enabled: false
  duplication:
    enabled: false
    config:
      languages:
        ruby:
          mass_threshold: 18
  flog:
      enabled: false
  git-legal:
    enabled: false
  markdownlint:
    enabled: false
  reek:
    enabled: false
  rubocop:
    enabled: true
    channel: rubocop-0-76
exclude_patterns:
  - "spec/"
